// app/components/feed-grid.tsx
/**
 * FeedGrid — responsive title grid with an IntersectionObserver sentinel for
 * infinite scroll and skeleton cards while a batch loads.
 */

import { useEffect, useRef } from "react";

import { Skeleton } from "~/components/ui/skeleton";
import { TitleCard } from "~/components/title-card";
import type { FeedItem } from "~/lib/schemas";

const GRID_CLASSES =
  "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-x-4 gap-y-6";

interface FeedGridProps {
  items: FeedItem[];
  hasMore: boolean;
  loading: boolean;
  onLoadMore: () => void;
  onSelect?: (item: FeedItem) => void;
}

export function FeedGrid({
  items,
  hasMore,
  loading,
  onLoadMore,
  onSelect,
}: FeedGridProps) {
  const sentinelRef = useRef<HTMLDivElement>(null);

  // Observe the sentinel; guard against firing while a fetch is in flight —
  // the loading dep re-creates the observer after each batch so a still-visible
  // sentinel triggers the next load.
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel || !hasMore) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting) && !loading) onLoadMore();
      },
      { rootMargin: "600px" }
    );
    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [hasMore, loading, onLoadMore]);

  return (
    <div>
      <div className={GRID_CLASSES}>
        {items.map((item) => (
          <TitleCard key={item.tmdbId} item={item} onSelect={onSelect} />
        ))}
        {loading &&
          Array.from({ length: 12 }, (_, i) => (
            <div key={`skeleton-${i}`} className="flex flex-col">
              <Skeleton className="mt-[23px] aspect-[2/3] w-full rounded-lg" />
              <Skeleton className="mt-2 h-4 w-3/4" />
              <Skeleton className="mt-1 h-3 w-1/2" />
            </div>
          ))}
      </div>

      {hasMore && <div ref={sentinelRef} className="h-px" />}

      {!hasMore && items.length > 0 && (
        <p className="py-10 text-center text-sm text-muted-foreground">
          You've reached the end.
        </p>
      )}
    </div>
  );
}

// src/lib/components/feed-grid.svelte
<script lang="ts">
	import { Skeleton } from '$lib/components/ui/skeleton';
	import TitleCard from '$lib/components/title-card.svelte';
	import type { FeedItem } from '$lib/schemas';

	interface Props {
		items: FeedItem[];
		hasMore: boolean;
		loading: boolean;
		onloadmore: () => void;
		onselect?: (item: FeedItem) => void;
	}

	let { items, hasMore, loading, onloadmore, onselect }: Props = $props();

	let sentinel = $state<HTMLElement>();

	// Observe the sentinel; the effect re-runs when loading flips, so a
	// still-visible sentinel triggers the next batch after each load.
	$effect(() => {
		if (!sentinel || !hasMore) return;
		const isLoading = loading;

		const observer = new IntersectionObserver(
			(entries) => {
				if (entries.some((e) => e.isIntersecting) && !isLoading) onloadmore();
			},
			{ rootMargin: '600px' }
		);
		observer.observe(sentinel);
		return () => observer.disconnect();
	});
</script>

<!-- FeedGrid — responsive title grid with an IntersectionObserver sentinel
     for infinite scroll and skeleton cards while a batch loads. -->
<div>
	<div class="grid grid-cols-2 gap-x-4 gap-y-6 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
		{#each items as item (item.tmdbId)}
			<TitleCard {item} {onselect} />
		{/each}
		{#if loading}
			{#each Array.from({ length: 12 }, (_, i) => i) as i (i)}
				<div class="flex flex-col">
					<Skeleton class="mt-[23px] aspect-[2/3] w-full rounded-lg" />
					<Skeleton class="mt-2 h-4 w-3/4" />
					<Skeleton class="mt-1 h-3 w-1/2" />
				</div>
			{/each}
		{/if}
	</div>

	{#if hasMore}
		<div bind:this={sentinel} class="h-px"></div>
	{:else if items.length > 0}
		<p class="text-muted-foreground py-10 text-center text-sm">You've reached the end.</p>
	{/if}
</div>
