// app/components/title-card.tsx
/**
 * TitleCard — poster card with the score lip, title, and metadata line.
 * The primary card used across the discovery feed. See docs/PRD.md §3.
 */

import { Video } from "lucide-react";

import { getImageUrl } from "~/lib/tmdb";
import type { FeedItem } from "~/lib/schemas";
import type { ScoreBreakdown } from "~/lib/mdblist";
import {
  ScoreLip,
  getScoreTier,
  getTierBorderClass,
} from "~/components/score-badge";
import { cn } from "~/lib/utils";

interface TitleCardProps {
  item: FeedItem;
  onSelect?: (item: FeedItem) => void;
}

export function TitleCard({ item, onSelect }: TitleCardProps) {
  const posterUrl = getImageUrl(item.posterPath, "poster", "medium");
  const year = item.releaseDate ? new Date(item.releaseDate).getFullYear() : null;
  const isUnreleased = item.releaseDate
    ? new Date(item.releaseDate) > new Date()
    : false;
  const tier = getScoreTier(item.score, isUnreleased);

  return (
    <button
      type="button"
      className="group relative flex flex-col text-left cursor-pointer"
      onClick={() => onSelect?.(item)}
      aria-label={item.title}
    >
      {/* Score lip — right-aligned above the poster */}
      <div className="self-end mr-2">
        <ScoreLip
          score={item.score}
          tmdbId={item.tmdbId}
          isUnreleased={isUnreleased}
          sourceCount={item.sourceCount}
          breakdown={item.breakdown as ScoreBreakdown | undefined}
        />
      </div>

      {/* Poster — top border matches the lip gradient's dark end */}
      <div
        className={cn(
          "relative w-full overflow-hidden bg-muted aspect-[2/3] rounded-lg shadow-lg border-t-2",
          getTierBorderClass(tier)
        )}
      >
        {posterUrl ? (
          <img
            src={posterUrl}
            alt={item.title}
            loading="lazy"
            width="342"
            height="513"
            className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center text-muted-foreground/40">
            <Video className="size-12" strokeWidth={1.5} />
          </div>
        )}
      </div>

      <h3 className="mt-2 w-full text-sm font-medium truncate leading-tight">
        {item.title}
      </h3>

      {/* Metadata row: type • year (matches modal style) */}
      <div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground">
        <span>{item.mediaType === "tv" ? "TV Show" : "Movie"}</span>
        {year && (
          <>
            <span>•</span>
            <span>{year}</span>
          </>
        )}
      </div>
    </button>
  );
}

// src/lib/components/title-card.svelte
<script lang="ts">
	import Video from '@lucide/svelte/icons/video';

	import ScoreLip, { getScoreTier, getTierBorderClass } from '$lib/components/score-lip.svelte';
	import { getImageUrl } from '$lib/tmdb';
	import type { FeedItem } from '$lib/schemas';
	import type { ScoreBreakdown } from '$lib/mdblist';
	import { cn } from '$lib/utils';

	interface Props {
		item: FeedItem;
		onselect?: (item: FeedItem) => void;
	}

	let { item, onselect }: Props = $props();

	const posterUrl = $derived(getImageUrl(item.posterPath, 'poster', 'medium'));
	const year = $derived(item.releaseDate ? new Date(item.releaseDate).getFullYear() : null);
	const isUnreleased = $derived(item.releaseDate ? new Date(item.releaseDate) > new Date() : false);
	const tier = $derived(getScoreTier(item.score, isUnreleased));
</script>

<!-- TitleCard — poster card with the score lip, title, and metadata line. -->
<button
	type="button"
	class="group relative flex cursor-pointer flex-col text-left"
	onclick={() => onselect?.(item)}
	aria-label={item.title}
>
	<!-- Score lip — right-aligned above the poster -->
	<div class="mr-2 self-end">
		<ScoreLip
			score={item.score}
			tmdbId={item.tmdbId}
			{isUnreleased}
			sourceCount={item.sourceCount}
			breakdown={item.breakdown as ScoreBreakdown | undefined}
		/>
	</div>

	<!-- Poster — top border matches the lip gradient's dark end -->
	<div
		class={cn(
			'bg-muted relative aspect-[2/3] w-full overflow-hidden rounded-lg border-t-2 shadow-lg',
			getTierBorderClass(tier)
		)}
	>
		{#if posterUrl}
			<img
				src={posterUrl}
				alt={item.title}
				loading="lazy"
				width="342"
				height="513"
				class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
			/>
		{:else}
			<div class="text-muted-foreground/40 flex h-full w-full items-center justify-center">
				<Video class="size-12" strokeWidth={1.5} />
			</div>
		{/if}
	</div>

	<h3 class="mt-2 w-full truncate text-sm leading-tight font-medium">
		{item.title}
	</h3>

	<!-- Metadata row: type • year (matches modal style) -->
	<div class="text-muted-foreground mt-1 flex items-center gap-1 text-xs">
		<span>{item.mediaType === 'tv' ? 'TV Show' : 'Movie'}</span>
		{#if year}
			<span>•</span><span>{year}</span>
		{/if}
	</div>
</button>
